apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: prometheus
    release: zyg
    chart: prometheus-14.3.0
    heritage: Helm
  name: zyg-grafana-server
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "rook-ceph-block"
  resources:
    requests:
      storage: "10Gi"

